version: '2'
services:
  odoo:
    image: odoo
    ports:
      - "8082:8069"
    links:
      - db
    volumes:
      - odoo-filestore:/var/lib/odoo
      - odoo-config:/etc/odoo
      - odoo-custom-addons:/mnt/extra-addons
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    
volumes:
  odoo-custom-addons:
    driver: rancher-nfs
    external: true
  odoo-filestore:
    driver: rancher-nfs
  odoo-config:
    driver: rancher-nfs
  odoo-db-data:
    driver: rancher-nfs