version: '2'
services:
  orientdb:
    image: orientdb
    environment:
      - ORIENTDB_ROOT_PASSWORD=${root_pwd}
    ports:
      - "8106:2424"
      - "8107:2480"
    volumes:
      - config:/orientdb/config
      - databases:/orientdb/databases
      - backup:/orientdb/backup

volumes:
  config:
    driver: rancher-nfs
  databases:
    driver: rancher-nfs
  backup:
    driver: rancher-nfs