version: '2'
services:
  neo4j:
    image: neo4j
    restart: always
    volumes:
    - neo4j-mrp3-data:/data
    ports:
    - 7484:7474/tcp
    - 7697:7687/tcp
    labels:
      io.rancher.container.pull_image: always
  web:
    image: dstadel/odoo:12.0
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
    - odoo-mrp3-data:/var/lib/odoo
    - odoo-mrp3-config:/etc/odoo
    - odoo-mrp3-addons:/mnt/extra-addons
    ports:
      - "${odoo_port}:8069"
  db:
    image: postgres:11
    labels:
      io.rancher.container.pull_image: always
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    volumes:
    - odoo-mrp3-db-data:/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    labels:
      io.rancher.container.pull_image: always
    restart: always
    ports:
    - 8488:8080

