che:
  image: eclipse/che-server:latest
  tty: true
  environment:
    - CHE_HOST=173.212.243.187
    - CHE_MULTIUSER=false
    - CHE_DOCKER_IP_EXTERNAL=173.212.243.187
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/che/data:/data
  ports:
    - "8120:8080"
    - "5050:5050"
    - "32768:32768"
    - "32769:32769"
    - "32770:32770"
    - "32771:32771"
  labels:
    io.rancher.container.pull_image: always