che:
  image: eclipse/che:latest
  tty: true
  environment:
    - CHE_HOST=173.212.243.187
    - CHE_PORT=8080
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/che/data:/data
  ports:
    - "8120:8080"
    - "8121:5000"
  labels:
    io.rancher.container.pull_image: always