che:
  image: eclipse/che:latest
  tty: true
  environment:
    - CHE_HOST=173.212.243.187
    - CHE_MULTIUSER=true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/che/data:/data
  ports:
    - "8120:8080"
    - "5050:5050"
    - "32768-65535:32768-65535"
  labels:
    io.rancher.container.pull_image: always
  network_mode: "bridge"